insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("맥북","전자기기",300,"APPLE", 50, "13인치 최신형")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("이지부스트","잡화",30,"아디다스",300, "콜라보 제품")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("애플펜슬","전자기기",10,"APPLE", 500, "애플패드와 찰떡")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("BMW X5","CAR",10000,"BMW", 100, "BMW회사 X5")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("BMW X3","CAR",10000,"BMW", 150, "BMW회사 X3")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("그램노트북","전자기기",200,"LG전자", 3000, "17인치 최신형")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("포르쉐 911","CAR",30000,"포르쉐", 100, "최고의 간지작살 자동차")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("삼성노트북","전자기기",1000,"삼성전자", 500, "15인치 노트북")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("에어팟","전자기기",20,"APPLE", 1000, "애플의 구형 에어팟")
insert into product_table(name,category,price,manufacturer,unit_In_Stock,description) values ("에어팟프로","전자기기",30,"APPLE", 5000, "노이즈 캔슬링이 가능한 에어팟 프로")